name = "OptiFloat"
uuid = "704b4457-c485-4fbe-a8ad-b77f6dbf1f10"
authors = ["Niklas Heim <heim.niklas@gmail.com>"]
version = "0.1.0"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"

[compat]
IntervalArithmetic = "0.22.12"
