name = "OptiFloat"
uuid = "704b4457-c485-4fbe-a8ad-b77f6dbf1f10"
authors = ["Niklas Heim <heim.niklas@gmail.com>"]
version = "0.1.0"

[deps]
DynamicExpressions = "a40a106e-89c9-4ca8-8020-a735e8728b6b"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Metatheory = "e9d8d322-4543-424a-9be4-0cc815abe26c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
DynamicExpressions = "0.17.0"
IntervalArithmetic = "0.22.12"
Metatheory = "3.0.0"
Statistics = "1"
TermInterface = "1"
