name = "OptiFloat"
uuid = "704b4457-c485-4fbe-a8ad-b77f6dbf1f10"
authors = ["Niklas Heim <heim.niklas@gmail.com>"]
version = "0.1.0"

[deps]
DynamicExpressions = "a40a106e-89c9-4ca8-8020-a735e8728b6b"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Metatheory = "e9d8d322-4543-424a-9be4-0cc815abe26c"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[sources]
DynamicExpressions = {rev = "nh/early-exit", url = "https://github.com/nmheim/DynamicExpressions.jl"}
Metatheory = {rev = "ale/3.0", url = "https://github.com/JuliaSymbolics/Metatheory.jl"}

[compat]
Printf = "1.11.0"
Term = "2.0.6"
TermInterface = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
