[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
OptiFloat = "704b4457-c485-4fbe-a8ad-b77f6dbf1f10"
DynamicExpressions = "a40a106e-89c9-4ca8-8020-a735e8728b6b"
Metatheory = "e9d8d322-4543-424a-9be4-0cc815abe26c"

[sources]
OptiFloat = {path = "../"}
Metatheory = {rev = "ale/3.0", url = "https://github.com/JuliaSymbolics/Metatheory.jl"}
DynamicExpressions = {url = "https://github.com/nmheim/DynamicExpressions.jl", rev="nh/early-exit"}

